services:
  base:
    init: true
    privileged: true
    env_file: [ "${ENV_FILE}" ]
    environment:
      - IMS_DOMAIN=ims.mnc${MNC03}.mcc${MCC}.3gppnetwork.org
      - EPC_DOMAIN=epc.mnc${MNC03}.mcc${MCC}.3gppnetwork.org
    volumes:
      - ${DOCKER}/volte:/mnt/volte:ro
    labels:
      o5gc.stack: ${O5GC_STACK}
      o5gc.webui.priority: ${WEBUI_PRIO_VOLTE}
    profiles: [ "volte" ]

  kamailio:
    extends:
      service: base
    image: o5gc/volte-kamailio
    entrypoint: [ "/mnt/volte/kamailio/entrypoint.sh" ]
    healthcheck:
      test: /bin/bash -c "TERM=dumb kamctl monitor 1 | grep -q up_since || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    dns: ${VOLTE_DNS_IP_ADDR}

  dns:
    extends:
      service: base
    image: o5gc/volte-dns
    container_name: volte-dns
    entrypoint: [ "/mnt/volte/dns/entrypoint.sh" ]
    networks:
      corenet:
        ipv4_address: ${VOLTE_DNS_IP_ADDR}
    labels:
      o5gc.stack: ${O5GC_STACK}

  icscf:
    extends:
      service: kamailio
    container_name: icscf
    command: icscf
    networks:
      corenet:
        ipv4_address: ${ICSCF_IP_ADDR}
    depends_on:
      fhoss:
        condition: service_started
      mysql:
        condition: service_healthy
      volte-dns:
        condition: service_started

  pcscf:
    extends:
      service: kamailio
    container_name: pcscf
    command: pcscf
    networks:
      corenet:
        ipv4_address: ${PCSCF_IP_ADDR}
    depends_on:
      icscf:
        condition: service_started
      mysql:
        condition: service_healthy
      rtpengine:
        condition: service_started
      scscf:
        condition: service_started
      volte-dns:
        condition: service_started

  scscf:
    extends:
      service: kamailio
    container_name: scscf
    command: scscf
    networks:
      corenet:
        ipv4_address: ${SCSCF_IP_ADDR}
    depends_on:
      fhoss:
        condition: service_healthy
      mysql:
        condition: service_healthy
      volte-dns:
        condition: service_started

  smsc:
    extends:
      service: kamailio
    container_name: smsc
    command: smsc
    networks:
      corenet:
        ipv4_address: ${SMSC_IP_ADDR}
    depends_on:
      mysql:
        condition: service_healthy
      volte-dns:
        condition: service_started
    profiles: [ "smsc" ]
    dns: ${VOLTE_DNS_IP_ADDR}

  rtpengine:
    extends:
      service: base
    image: o5gc/volte-rtpengine
    container_name: rtpengine
    entrypoint: [ "/mnt/volte/rtpengine/entrypoint.sh" ]
    networks:
      corenet:
        ipv4_address: ${RTPENGINE_IP_ADDR}
    dns: ${VOLTE_DNS_IP_ADDR}

  fhoss:
    extends:
      service: base
    image: o5gc/volte-fhoss
    container_name: fhoss
    entrypoint: [ "/mnt/volte/fhoss/entrypoint.sh" ]
    environment:
      - SMS_DOMAIN=${SMS_DOMAIN:-SMS-over-IMS}
    networks:
      corenet:
        ipv4_address: ${VOLTE_HSS_IP_ADDR}
      o5gc:
    ports:
      - ${O5GC_WEBUI_HOST_ADDR}:${FHOSS_HOST_PORT}:8080
    labels:
      o5gc.link.title: "FHOSS"
      o5gc.link.url: "http://{{host}}:${FHOSS_HOST_PORT}/"
    depends_on: [ volte-dns ]
    healthcheck:
      test: bash -c "exec 6<> /dev/tcp/localhost/8080"
    dns: ${VOLTE_DNS_IP_ADDR}

  pyhss:
    extends:
      service: base
    image: o5gc/volte-pyhss
    container_name: pyhss
    entrypoint: [ "/mnt/volte/pyhss/entrypoint.sh" ]
    networks:
      corenet:
        ipv4_address: ${VOLTE_HSS_IP_ADDR}
      o5gc:
    depends_on: [ mysql, volte-dns ]
    dns: ${VOLTE_DNS_IP_ADDR}
