services:
  sigdigger:
    image: o5gc/misc-sigdigger
    container_name: sigdigger
    entrypoint: /o5gc/SigDigger/entrypoint.sh
    privileged: true
    env_file: [ "${ENV_FILE}" ]
    environment:
      - DISPLAY
    volumes:
      - ./sigdigger-entrypoint.sh:/o5gc/SigDigger/entrypoint.sh:ro
      - ${BASE}/scripts/band_helper.py:/o5gc/SigDigger/scripts/band_helper.py:ro
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    profiles: [ "sigdigger" ]

  osmocom_fft:
    image: o5gc/misc-gr-osmosdr
    container_name: osmocom_fft
    entrypoint: bash -xc "osmocom_fft -a uhd"
    privileged: true
    env_file: [ "${ENV_FILE}" ]
    environment:
      - DISPLAY
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    profiles: [ "osmocom_fft" ]

  ltesniffer:
    image: o5gc/misc-ltesniffer
    container_name: ltesniffer
    entrypoint: /o5gc/ltesniffer/entrypoint.sh
    privileged: true
    env_file: [ "${ENV_FILE}" ]
    environment:
      - SNIFF_BAND=${SNIFF_BAND:-${EUTRA_BAND}}
      - SNIFF_ARFCN=${SNIFF_ARFCN:-${EUTRA_ARFCN_DL}}
      - SNIFF_CELL_SEARCH=${SNIFF_CELL_SEARCH:-1}
      - SNIFF_CELL_PCI
      - SNIFF_CELL_PRB
      - SNIFF_SECURITY_API=${SNIFF_SECURITY_API:-3}
      - SNIFF_DEBUG
    volumes:
      - ./ltesniffer-entrypoint.sh:/o5gc/ltesniffer/entrypoint.sh:ro
      - ${BASE}/scripts/band_helper.py:/o5gc/band_helper.py:ro
      - /dev/bus/usb:/dev/bus/usb
    profiles: [ "ltesniffer" ]

  swagger-ui:
    image: o5gc/misc-swagger
    container_name: swagger-ui
    env_file: [ "${ENV_FILE}" ]
    environment:
      - CONFIG_URL=./swagger-config.json
      - HOST_DEFAULT_ROUTE_IFACE_IP=${DEFAULT_ROUTE_IFACE_IP:-}
    volumes:
      - ./swagger-config.json:/usr/share/nginx/html/swagger-config.json:ro
      - ./swagger-entrypoint.sh:/docker-entrypoint.d/99-o5gc.sh:ro
    networks:
      - corenet
      - o5gc
    ports:
      - ${O5GC_WEBUI_HOST_ADDR}:${SWAGGER_UI_HOST_PORT}:8288
    profiles: [ "swagger-ui" ]
