services:
  gnb:
    extends:
      file: ${DOCKER}/ueransim/services.yaml
      service: ueransim-gnb

  ue:
    extends:
      file: ${DOCKER}/ueransim/services.yaml
      service: ueransim-ue

  mongo:
    extends:
      file: ${DOCKER}/open5gs/services.yaml
      service: mongo
  mongo-express:
    extends:
      file: ${DOCKER}/open5gs/services.yaml
      service: mongo-express

  nrf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: nrf

  upf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: upf

  amf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: amf

  ausf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: ausf

  nssf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: nssf

  pcf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: pcf

  smf:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: smf

  udm:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: udm

  udr:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: udr

  free5gc-webui:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: free5gc-webui

  free5gc-init:
    extends:
      file: ${DOCKER}/free5gc/services.yaml
      service: free5gc-init
